### ISSUE TITLE
issue de ejemplo

### ISSUE THREAD

**Issue by magdalenaviloriac** [maestria-geotel-201902/unidad-0-asignacion-1-asig-conrstudio-issues-aleira#2]
no tengo un problema  todo esta  concreto
* itálica
**negrita**

**Comment by geofis** [comment]
Como comenté en el *commit*, supongo @magdalenaviloriac que ya tienes tu repo con *commit* e *issue* hechos. Evita este cruce de asignaciones en el futuro. Recuerda @magdalenaviloriac, verifica el sufijo del nombre del repo, debe aparecer tu nombre de usuario.
